apply from: "https://raw.githubusercontent.com/ixDarkLorD/ModResources/main/gradle/v3/fabric.gradle"
apply from: rootProject.file("testmods/testmod.gradle")

dependencies {
    api libs.jei.api.fabric
    implementation libs.jei.fabric

    implementation project(":fabric")
    implementation project(":canvas-fabric")
}
