modLoader = "javafml"
loaderVersion = "[${min_neoforge_fml_version},)"
issueTrackerURL = "${mod_issue_url}"
license = "${mod_license}"

[[mods]]
modId = "${modid}"
displayName = "${mod_name}"
version = "${mc_version}-${mod_version}"
description = "${mod_description}"
authors = "${mod_author}"
logoFile = "mod_logo.png"
updateJSONURL = "${mod_neoforge_update_url}"

# A library: mod lists like Glazed Menu show it under Libraries.
[modproperties.${modid}]
library = true

[[mixins]]
config = "${modid}.common.mixins.json"

[[dependencies.${modid}]]
modId = "coolcatcore"
type = "required"
versionRange = "[${mc_version}-${mod_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${modid}]]
modId = "neoforge"
type = "required"
versionRange = "[${project.supported_min_neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modid}]]
modId = "minecraft"
type = "required"
versionRange = "[${project.supported_min_mc_version},${max_mc_version}]"
ordering = "NONE"
side = "BOTH"
