modLoader="javafml"
loaderVersion="[${min_forge_fml_version},)"
issueTrackerURL="${mod_issue_url}"
license="${mod_license}"
logoFile="mod_logo.png"

[[mods]]
modId="${modid}"
version="${mod_version}"
displayName="${mod_name}"
description="${mod_description}"
authors="${mod_author}"
displayURL="${mod_page_url}"
updateJSONURL="${mod_forge_update_url}"
displayTest="${mod_forge_display_test}"

[[dependencies.${modid}]]
modId="forge"
mandatory=true
versionRange="[${min_forge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${modid}]]
modId="minecraft"
mandatory=true
versionRange="[${mc_version},) , (,${max_mc_version}]"
ordering="NONE"
side="BOTH"

[modproperties.${modid}]
catalogueImageIcon="mod_logo.png"
configuredBackground="minecraft:textures/block/gold_block.png"