modLoader = "javafml"
loaderVersion = "[${min_neoforge_fml_version},)"
issueTrackerURL = "${mod_issue_url}"
license = "${mod_license}"

[[mods]]
modId = "${modid}"
displayName = "${mod_name}"
version = "${mod_version}"
description = "${mod_description}"
authors = "${mod_author}"
logoFile = "mod_logo.png"
updateJSONURL = "${mod_neoforge_update_url}"

[[dependencies.${modid}]]
modId = "neoforge"
type = "required"
versionRange = "[${min_neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modid}]]
modId = "minecraft"
type = "required"
versionRange = "[${mc_version},) , (,${max_mc_version}]"
ordering = "NONE"
side = "BOTH"
