modLoader="javafml"
loaderVersion="[${min_forge_fml_version},)"
issueTrackerURL="${mod_issue_url}"
license="${mod_license}"
logoFile="mod_logo.png"

[[mods]]
modId="testingmod"
version="1.0.0"
displayName="Testing Mod"
authors="ixDarkLorD"
displayTest="${mod_forge_display_test}"

[[dependencies.testingmod]]
modId="forge"
mandatory=true
versionRange="[${min_forge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.testingmod]]
modId="minecraft"
mandatory=true
versionRange="[${mc_version},) , (,${max_mc_version}]"
ordering="NONE"
side="BOTH"