apply from: "https://raw.githubusercontent.com/ixDarkLorD/ModResources/main/gradle/v1/forge.gradle"

loom {
    runs {
        client {
            setConfigName("${helper.uppercaseFirstChar(project.name)} Client ${libs.versions.minecraft.get()}")
        }
        server {
            setConfigName("${helper.uppercaseFirstChar(project.name)} Server ${libs.versions.minecraft.get()}")
        }
    }
}

dependencies {
    modApi libs.jei.api.forge
    modImplementation libs.jei.forge

    implementation project(path: ":forge", configuration: "namedElements")
}